### ISSUE TITLE
Command line frame range error when out point out of range

### ISSUE THREAD

**Issue by PiOverFour** [darbyjohnston/DJV#240]
Hi, thanks a lot for the new command line options!

I stumbled upon a bug while testing playback from Blender: when the `-in_out` option’s second value is greater than the last rendered frame of the sequence, the two In/Out points misbehave: it looks like the first value is set as Out point, while the In point is set to the first actual frame in the sequence.
So if you have a sequence in the range 10-20:
- if you specify `-in_out 5 20`, it will work as expected, play the whole sequence,
- if you specify `-in_out 5 25`, it will actually play only frame 10 instead of 10-20,
- if you specify `-in_out 15 25`, it will actually play 10-15 instead of 15-20.

This situation could happen easily if you start rendering a sequence, cancel it in the middle and play back the frames rendered until then.

EDIT: There is also a problem when specifying an out of range `-frame`: DJV does not start. This may happen when scrubbing the timeline in a DCC if the current frame has not yet been rendered.

**Comment by darbyjohnston** [comment]
Hi, thanks for catching this, it looks like I was clamping the frames wrong. This reminds me I need to start writing confidence tests for the DJV application. :)

Also as I mentioned in the other issue I didn't include the pixel aspect command-line option in this round of changes, but if you think it would be useful we can open a new issue for options for the next version.

I've checked in a change that has this new behavior:
* If the in frame is not valid the start frame is used
* If the out frame is not valid the end frame is used
* The frame is clamped to the in and out points

**Comment by PiOverFour** [comment]
> I've checked in a fix that has this new behavior:

I’m trying to test this, but now I’m getting _ERROR: Path does not exist_ and DJV doesn’t start when using padding or frame range. The sequence opens when specifying a single image, though. And _then_ the clamping works as expected!

> Also as I mentioned in the other issue I didn't include the pixel aspect command-line option in this round of changes, but if you think it would be useful we can open a new issue for options for the next version.

I don’t need it myself since I do mostly video with square pixels and no exotic format, but I figured it may be useful for some film pipelines, if the ratio specified in the file was lost at some point during conversion, e.g. ripping some letterboxed media. But now I’m not sure this has ever happened to me…

**Comment by darbyjohnston** [comment]
Could you post the command-line and file sequence you are using? The various tests I'm trying seem to work so far, using a sequence like "test_pattern.0001-1200.tif":
```
> djv \Users\darby\Desktop\Seq\Pad\test_pattern.0001.tif -in_out 100 200
> djv \Users\darby\Desktop\Seq\Pad\test_pattern.0001-1000.tif -in_out 100 200
> djv \Users\darby\Desktop\Seq\Pad\test_pattern.####.tif -in_out 100 200
> djv \Users\darby\Desktop\Seq\Pad\test_pattern.####.tif -in_out 100 2000
> djv \Users\darby\Desktop\Seq\Pad\test_pattern.####.tif -in_out -100 2000
```

**Comment by PiOverFour** [comment]
This is very strange — I can’t get it to work with any sequence, really. For instance,
the generated sequence
```
djv_test_pattern test.0001.tif
```
works only by calling
```
djv test.0001.tif
```
(or any existing frame).

**Comment by darbyjohnston** [comment]
Sorry it looks like it is working on Windows but not Linux, checking it out...

**Comment by darbyjohnston** [comment]
OK, I just checked in a change that should fix it, try syncing+building again and see if it works OK for you now.

**Comment by PiOverFour** [comment]
After compiling, I still get `ERROR: Path does not exist` with every sequence in the latest commit.

**Comment by darbyjohnston** [comment]
Gah, sorry again, looks like there was still a problem with files in the current directory. I just checked in a fix for that as well (hopefully). Thanks for putting up with this testing!

**Comment by PiOverFour** [comment]
I rebuilt from scratch and now it is working. So there was probably some problem with my build environment — sorry about that.
Anyway this appears fixed, thanks!

**Comment by darbyjohnston** [comment]
Great, thanks for testing it!
